### ISSUE TITLE
Habbo.com.tr Update

### ISSUE THREAD

**Issue by AlwahaL** [gerbenjacobs/habbowidgets-language#13]
`<?php
return [
    // Menu
    "Habinfo" => "Habinfo", // This is the actual name of the widget, probably keep it like this
    "Habbos" => "Habbolar",
    "Birthdays" => "Doğum Günleri",
    "Badges" => "Rozetler",
    "All badges" => "Bütün Rozetler",
    "Badge top x" => "Rozet Top %d", // %d will be replaced by the number
    "Achievements top x" => "Toplam Başarılar Top %d",
    "Unique badge top x" => "Benzersiz Rozetler Top %d", // 'Unique' is chosen as they're not technically 'rares'.
    "Badge owners" => "Rozet Sahipleri",
    "News" => "Haberler",
    "About" => "Hakkımızda",

    // Layout
    "Copyright" => "Copyright",
    /* -- "Made with :love: by :link: using the :link:" */
    // Habbies.nl tarafından yapıldı ❤ HabboAPI kullanarak
    "Made with" => "Yapıldı",
    "by" => "tarafından",
    "using the" => "kullanarak",
    "Generated in" => "Burada yapıldı",
    "Current server time" => "Güncel server saati",

    // Landing page
    "What's your Habbo name?" => "Habbo Kullanıcı adın ney?",
    /* -- Try to add the <br> at around 70 characters, so the next part goes on a new line */
    "landing_page_info" => "Tüm Habbolar hakkında daha fazla bilgi alabilirsin.<br>Mesela Personeller başka Habbolar veya Arkadaşınların Hakkında!",

    // General
    "Habbo" => "Habbo",
    "Hotel" => "Hotel",
    "Habbo name" => "Habbo Kullanıcı Adın ",
    "Oops.." => "Oops..",
    "from" => "burdan", // "Viewing page of :habbo: from :hotel:"
    "View Habinfo" => " Habbo Bilgisini ziyaret",
    "This hotel does not exist, redirecting you.." => "Bu otel bulunmakta değil başka yere yönlendiriyorsun..",

    // [habbo] Birthdays
    /* -- "Birthdays in Habbo.:hotel:" */
    "Birthdays in Habbo." => "Habboda doğum günüleri.",
    "Do you know anyone?" => "Bunlardan birini tanıyormusun?",
    "There are no birthdays in this hotel as far as we know?" => "Bu otelde bugünün doğum günü olanı bilmiyorsa ya sen?",
    "Pick another date" => "Başka bir tarih seç",
    "All years" => "Bütün Yıllar",
    "You have supplied an invalid date" => "Geçersiz bir tarih girdiniz",
    "This date lies in the future and can not be used" => "This date lies in the future and can not be used",

    // Habinfo Form
    "Find Habinfo on.." => "Habinfoyu buradan bulabilirsin..",
    "Find" => "Bul", // Button on the Habinfo form
    "Tip" => "İpucu",
    "Did you know you can also use a Direct URL to get to the Habbo you want to find?" => "Bunu biliyormuydun? Bir Habbo bulmak için direk Link kullanarak bulabilirsin!",
    "Just use the following format" => "Bunu kullan",
    "This hotel does not exist" => "Bu Hotel bulunmakta değil",
    "You forgot the Habbo name.." => "Habbo Kullanıcıadını unuttun..",
    "Extracting Habinfo of %s from Habbo.%s" => "%s from Habbo.%s yönlendiriliyorsun", // Leave the %s intact
    "Extracting Habinfo of someone from Habbo.%s" => "Herhangi bir Habbonun Habbo.%s Bilgisine yönlendiriliyorsun",

    /* -- "Looking for :name: on :hotel:" */
    "Looking for" => "Bunu aramaktayım",
    "someone" => "birisi",
    "on" => "on",
    "on_time" => "on", // could be different in languages other than English i.e. Dutch.
    "One moment.." => "Bir dakika..",
    "Something went wrong, we couldn't find that Habbo. Or they are banned.." => "Bir şeyler yanlış gitti.. bu Habboyu bulamadık veyada yasaklandı..",
    "Return to the Habinfo widget" => "Habinfo araçına geri dön",
    "Visit Habinfo history" => "Habboinfo Hikayesini ziyaret",
    "habinfo_user_banned" => "Bu Habbo Kullanıcısı yasaklandı bu yüzden hic bir bilgi bulamıyoruz.",

    // Habinfo
    "Closed profile, loading might take longer." => "Kapalı Profili olan Habbo Bilgisini öğrenmek biraz zaman alır.",
    "This Habbo is banned. We can not get any new information.." => "Bu Habbo Kullanıcısı yasaklandı yeni bilgi bulunamadık..",
    "Previous mottos" => "Eski motto",
    "Previous looks" => "Eski Tarzi",
    "Last online" => "Son oturum açma",
    "Last change" => "Son değişiklik",
    "Go to profile" => "Profile geç",
    "Closed profile" => "Kapalı Profil",
    "Banned" => "Bu Habbo Banlandı",
    "About me" => "Hakkımda",
    /* -- "Created on :date: and last updated :some time ago:" */
    "Created on" => "Tarıhınde açildi",
    "and last updated" => "ve en son güncellendi",
    "Friends" => "Arkadaşları",
    "Groups" => "Grupları",
    "Rooms" => "Odaları",
    "Photos" => "Resımlerı",
    "new" => "new", // Little label on new badges/friends etc. If your word is long (6+ characters), see if you can shorten it
    "This Habbo is not in the Habinfo system yet" => "Bu Habbo şuan Habbo sisteminde bulunmakta değil",
    "Show old badges" => "Eski Rozetleri göster",
    "Show old friends" => "Eski Arkadaşları göster",
    "Show old groups" => "Eski Gruplari göster",
    "Show old rooms" => "Eski Odalari göster",
    "Administrator" => "Admin", // Someone with admin rights in a group
    "Group created" => "Kuruluş tarihi",
    "Group joined" => "Gruba katılış tarihi",
    "Group updated" => "Grup Güncellendi",
    "Go to grouproom" => "Grup Odasina git",
    "Room created" => "Odanın Kuruluş Tarihi",
    "Room updated" => "Odanin güncellenme tarihi",
    "Rating" => "Puanlama",
    "Maximum visitors" => "Odanin toplan ziyaretcisi",
    "Go to room" => "Odaya git",
    // "Taken in this room on :date: and received :number: likes
    "Taken in" => "Kullanılmış",
    "this room" => "bu oda",
    "and received" => "ve bukadar aldi",
    "likes" => "beğeni",
    "Show on Habbo" => "Habboda göster",
    "Who else has this badge?" => "Bu Rozet başka kimde var?",
    "Removed" => "geri alindi",
    "%s has been a Habbo since %s and has %d badges, %d friends, %d groups and %d rooms!" => "%s has been a Habbo since %s and has %d badges, %d friends, %d groups and %d rooms!", // Leave the %s and %d intact
    "Back to top" => "başa dön",
    "Go to Badges" => "Rozetlere git",
    "Go to Friends" => "Arkadaşlara git",
    "Go to Groups" => "Gruplara git",
    "Go to Rooms" => "Odalara git",
    "Go to Photos" => "Fotolara git",
    "Toggle achievements" => "Toggle achievements",
    "Toggle unique badges" => "Toggle unique badges",

    // Maintenance
    "Maintenance.." => "Bakım Arası..",
    "maintenance_paragraph_one" => "Selam Habbo! Sayfaya bir kaç yenilik katıyoruz.",
    "maintenance_paragraph_two" => "Bizimle kal! Yakınde geri dönecez!",
    "Follow us on Twitter for updates" => "Bizi Twitter da takip eti!",

    // 404
    "Oops, page not found" => "Oops, sayfa bulunamadı",
    "The page you tried to request doesn't exist.." => "Gitmek istediğin Sayfa bulunamiyor ..",
    "page_not_found_paragraph" => "Üzülme.. Sayfaya geri dön. %sAnasayfa%s veya habbo %sdoğum günülerine%s bak!", // Leave the %s intact, they will become links
    "Return" => "Geri dön",

    // Badges
    "Achievement top x for" => "Toplam Başarı top %d", // "Achievement top x for :hotel:"
    "Last updated" => "Son güncelleme",
    "Badge top x for" => "Toplam Rozet top %d",
    "Unique badge top x for" => "Unique badge top %d for",
    "All x badges in" => "Tüm Rozetler %s bu Otelde", // Leave the %s intact; "All :number: badges in :hotel:"
    "First discovered" => "keşfedilen gün",
    "Find out which Habbos own a specific badge!" => "Nadir rozet sahip olanlara bak!",
    "Only 1 Habbo in Habbo.%s owns the %s badge" => "Tek bir Habboda bulunuyor bu rozet %s", // Leave the %s intact
    "%d Habbos in Habbo.%s own the %s badge" => "%d Habbolarda Otelinde.%s bu rozete sahipler %s ", // Leave the %s and %d intact -- "15 Habbos in Habbo.com own the ADM badge"
    "Sorry, we don't know anyone who has this badge" => "Kusura bakma ama bu Rozet kimde bulunduğunu bilmiyoruz",
    "Only one Habbo has this badge.." => "Tek bir Habboda bulunuyor bu rozet..",
    "Habbos have this badge.." => "Habbolarda bu Rozet bulunuyor..", // ":number: Habbos have this badge.."
    "So we can not show them all." => "Bu yüzden hepsini gösteremiyoruz.",
    "Find Habbos who own.." => "Hangi Habbolarda bulunan Rozetleri bul..",
    "Badge code" => "Rozet kodu",
    "Why don't you check out.." => "Buraya neden bakmıyorsun..",
    "unique badges in" => "Nadir Rozet", // ":number: unique badges in :hotel:"
    "owners" => "Sahıplerı",
    "There are no unique badges in this hotel.." => "Bu Otelde nadir rozet bulunmuyor..",

    // Time
    "today" => "bugün",
    "and" => "ve",
    "ago" => "önce",
    "hours" => "Saat",
    "years" => "Sene",
    "months" => "Ay",
    "days" => "Gün",

    // Habbo Ticker
    "Latest updates from Habbo Ticker" => "Habbo Ticker'den son güncellemeler",
    // This habbo added more than 5 new badges, 3 new groups and changed their look
    "changed their motto" => "Mottosunu değiştirdi",
    "changed their look" => "Kıyafetini değiştirdi",
    "more than x" => "Daha fazla %d",
    "new badge(s)" => "Yeni Rozet(s)",
    "new group(s)" => "Yeni Grup(s)",
    "new room(s)" => "Yeni Oda(s)",
    "new friend(s)" => "Yeni Arkadaş(s)",
    "new photo(s)" => "Yeni Resim(s)",
    "joined" => "Katıldı", // This habbo joined Habbowidgets
    "added" => "Eklendi", // you can also replace this with "has"
];
`

https://www.habbo.com.tr/profile/talliboali

fix the wrong places and i changed habbo ticker

**Comment by gerbenjacobs** [comment]
Thanks @AlwahaL - I've updated the site with your translations!
