### ISSUE TITLE
Three translations for Habbo Birthdays

### ISSUE THREAD

**Issue by gerbenjacobs** [gerbenjacobs/habbowidgets-language#2]
**Description**
With the latest feature to choose a date in the Habbo Birthdays page, we've added 3 new translations.

**Translations**
```
    // [habbo] Birthdays
    "All years" => "All years",
    "You have supplied an invalid date" => "You have supplied an invalid date",
    "This date lies in the future and can not be used" => "This date lies in the future and can not be used",
```
**Todo**
- [x] com.br.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/com.br.php#L44)
- [x] com.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/com.php#L44)
- [x] com.tr.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/com.tr.php#L45)
- [x] de.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/de.php#L44)
- [x] dk.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/dk.php#L44)
- [x] es.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/es.php#L44)
- [x] fi.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/fi.php#L45)
- [x] fr.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/fr.php#L44)
- [x] it.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/it.php#L44)
- [x] nl.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/nl.php#L44)

**Comment by MattiaDes** [comment]
Italian done
