### ISSUE TITLE
Two translations for the new buttons in the Badge section

### ISSUE THREAD

**Issue by gerbenjacobs** [gerbenjacobs/habbowidgets-language#4]
**Description**
Two new buttons have been added to the Badges section of Habinfo pages. For the translation you're also allowed to use "Show unique badges". For example in Dutch there's no real good translation for the word 'toggle'.

**Translations**
```
    // Habinfo
    "Toggle achievements" => "Toon achievements",
    "Toggle unique badges" => "Toon unieke badges",
```

**Todo**
- [x] com.br.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/com.br.php#L118)
- [x] com.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/com.php#L118)
- [x] com.tr.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/com.tr.php#L119)
- [x] de.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/de.php#L118)
- [x] dk.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/dk.php#L118)
- [x] es.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/es.php#L118)
- [x] fi.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/fi.php#L121)
- [x] fr.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/fr.php#L118)
- [x] it.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/it.php#L118)
- [x] nl.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/nl.php#L118)

**Comment by MattiaDes** [comment]
Italian done
