### ISSUE TITLE
Habbo Ticker translations

### ISSUE THREAD

**Issue by gerbenjacobs** [gerbenjacobs/habbowidgets-language#7]
The new Habbo Ticker widget on Habbowidgets requires some new translations strings.
If you want to help with this, check out the [readme of the project](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/README.md) to learn more.

**Translations**
```
    // Habbo Ticker
    "Latest updates from Habbo Ticker" => "Latest updates from Habbo Ticker",
    // This habbo added more than 5 new badges, 3 new groups and changed their look
    "changed their motto" => "changed their motto",
    "changed their look" => "changed their look",
    "more than x" => "more than %d",
    "new badge(s)" => "new badge(s)",
    "new group(s)" => "new group(s)",
    "new room(s)" => "new room(s)",
    "new friend(s)" => "new friend(s)",
    "new photo(s)" => "new photo(s)",
    "joined" => "joined", // This habbo joined Habbowidgets
    "added" => "added", // you can also replace this with "has"
```

**Todo**
- [x] com.br.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/com.br.php#L165)
- [x] com.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/com.php#L168)
- [x] com.tr.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/com.tr.php#L166)
- [x] de.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/de.php#L165)
- [x] dk.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/dk.php#L165)
- [x] es.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/es.php#L165)
- [x] fi.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/fi.php#L166)
- [x] fr.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/fr.php#L165)
- [x] it.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/it.php#L165)
- [x] nl.php - [Show](https://github.com/gerbenjacobs/habbowidgets-language/blob/master/nl.php#L168)

**Comment by MattiaDes** [comment]
Italian done!
